version: '3.4'
services:
  serverless-ts-backend:
    tty: true
    build:
      context: .
      target: development
    volumes: 
      - .:/src
    expose:
      - 3001
    ports:
      - "3001:3001"
    container_name: serverless-ts-backend

  serverless-ts-backend-test:
    tty: true
    build:
      context: .
      target: test
    volumes: 
      - .:/src
    container_name: serverless-ts-backend-test
    command: yarn test:coverage
